fragment MangaFragment on MangaType {
    artist
    author
    description
    id
    status
    thumbnailUrl
    title
    url
    genre
    inLibraryAt
    chapters {
        totalCount
    }
    latestUploadedChapter {
        uploadDate
    }
    latestFetchedChapter {
        fetchedAt
    }
    latestReadChapter {
        lastReadAt
    }
    unreadCount
    downloadCount
    source {
        displayName
    }
    realUrl
}

mutation GetMangaAndChapters($mangaId: Int!, $fetchManga: Boolean!, $fetchChapters: Boolean!) {
    fetchMangaAndChapters(input: {id: $mangaId, fetchManga: $fetchManga, fetchChapters: $fetchChapters}) {
        manga {
            ...MangaFragment
        }
        chapters {
            ...ChapterFragment
        }
    }
}

query GetMangaData($mangaId: Int!) {
    manga(id: $mangaId) {
        ...MangaFragment
    }
}

query SearchManga($filter: [MangaFilterInput!]) {
    mangas(
        condition: {inLibrary: true},
        filter: {
            and: $filter
        }
    ) {
        nodes {
            ...MangaFragment
        }
    }
}
